### ISSUE TITLE
Class SQLServerPlatform not found

### ISSUE THREAD

**Issue by Glideh** [intellectsoft-uk/MssqlBundle#1]
I get this message trying to use the bundle

> Fatal error: Class 'Doctrine\DBAL\Platforms\SQLServerPlatform' not found in /var/www/Symfony/vendor/bundles/Realestate/MssqlBundle/Platforms/DblibPlatform.php on line 40 

Here is my config.yml

``` yml
doctrine:
    dbal:
        default_connection:       default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            ssrs:
#                driver:   pdo_sqlsrv
                driver_class: \Realestate\MssqlBundle\Driver\PDODblib\Driver
                host:     xxx.xxx.xxx.xxx
                dbname:   xxxxx
                user:     xxxxx
                password: xxxxx
```

What can I be doing wrong ?
